baseURL = "https://fodhil-ben.github.io/f0dh1l/"
title = "My Personal Blog"
languageCode = "en"
languageName = "English"
theme = "LoveIt"
hasCJKLanguage = false
copyright = "2025 F0DH1L"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Pagination config
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# Menu config
[menu]

  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    title = ""
    pre = ""
    post = ""

  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    title = ""
    pre = ""
    post = ""


  [[menu.main]]
    weight = 3
    identifier = "about"
    name = "About"
    url = "/about/"
    title = ""
    pre = ""
    post = ""

# Theme Params
[params]
  defaultTheme = "dark"
  description = "This is my personal blog"

  [params.app]
      title = "My Personal Blog"


  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "images/zoro.jpg"
      title = ""
      subtitle = "0% talent 101% hard work"
      typeit = true
      social = true
      disclaimer = ""

    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "fodhil-ben"
    Linkedin = "fodhil-benhiba"
    X = "Benhibafodhil"
    Instagram = "fodhil_benhiba"
    Facebook = "fodhilbenhiba"
    HackTheBox = "1460204"
    TryHackMe = "0xF0DH1L"
    Phone = "+213797530466"
    Email = "benhibafodhil@gmail.com"
    HackerOne = "0xf0dh1l"

  [params.author]
    name = "F0DH1L"
    email = "benhibafodhil@gmail.com"
    link = ""

  [params.page]

    [params.page.library]

      [params.page.library.css]
        someCSS = "css/custom.css"

  # Header config

  [params.header]

    # desktop header mode ["fixed", "normal", "auto"]

    desktopMode = "fixed"

    # mobile header mode ["fixed", "normal", "auto"]

    mobileMode = "auto"

    #  Header title config

    [params.header.title]

      # URL of the LOGO

      logo = ""

      # title name

      name = "F0DH1L Blog"

      # you can add extra information before the name (HTML format is supported), such as icons

      pre = ""

      # you can add extra information after the name (HTML format is supported), such as icons

      post = ""

      #  whether to use typeit animation for title name

      typeit = false

 [params.footer]

    enable = true

    #  Custom content (HTML format is supported)

    custom = ''

    #  whether to show Hugo and theme info

    hugo = true

    #  whether to show copyright info

    copyright = true

    #  whether to show the author

    author = true

    # Site creation time

    since = 2025

[caches]
  [caches.images]
    dir = ':cacheDir/images'